// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WkhFrHq72riJ2gquM7lQN2qmG4tvpRU',
    appId: '1:387422186211:web:aa3c922c94d5957a4fb3d6',
    messagingSenderId: '387422186211',
    projectId: 'tharm-16f63',
    authDomain: 'tharm-16f63.firebaseapp.com',
    storageBucket: 'tharm-16f63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybyzLb9UtP0n75hpvRzLTNL_YITEaZEY',
    appId: '1:387422186211:android:860156797cd590db4fb3d6',
    messagingSenderId: '387422186211',
    projectId: 'tharm-16f63',
    storageBucket: 'tharm-16f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFQ73ME5aLJfqzS4DK8gf5OYTOYKhWuAU',
    appId: '1:387422186211:ios:277c1e7b9577fdea4fb3d6',
    messagingSenderId: '387422186211',
    projectId: 'tharm-16f63',
    storageBucket: 'tharm-16f63.appspot.com',
    iosClientId: '387422186211-9ud76i9h60v5dj4pitak6j327n3cik5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tharmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFQ73ME5aLJfqzS4DK8gf5OYTOYKhWuAU',
    appId: '1:387422186211:ios:277c1e7b9577fdea4fb3d6',
    messagingSenderId: '387422186211',
    projectId: 'tharm-16f63',
    storageBucket: 'tharm-16f63.appspot.com',
    iosClientId: '387422186211-9ud76i9h60v5dj4pitak6j327n3cik5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tharmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8WkhFrHq72riJ2gquM7lQN2qmG4tvpRU',
    appId: '1:387422186211:web:990765842ff00a894fb3d6',
    messagingSenderId: '387422186211',
    projectId: 'tharm-16f63',
    authDomain: 'tharm-16f63.firebaseapp.com',
    storageBucket: 'tharm-16f63.appspot.com',
  );
}
